# Etape de construction
FROM node:lts as builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Etape de déploiement
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]